### ISSUE TITLE
Add support for login via username & password

### ISSUE THREAD

**Issue by Integral-Tech** [gmg137/netease-cloud-music-gtk#287]
It will be better if netease-cloud-music-gtk supports login via username & password.

The [ncm-api](https://gitee.com/gmg137/netease-cloud-music-api) supports this feature (https://gitee.com/gmg137/netease-cloud-music-api/blob/master/src/lib.rs#L226), hence I think it's not difficult to implement it in netease-cloud-music-gtk.

**Comment by gmg137** [comment]
Interfaces that use user names and passwords often require secondary authentication (mobile phones or verification codes). These interfaces have strict requirements on IP addresses and other login environments. They are often blocked or even restricted for security reasons. Therefore, user names and passwords have been cancelled since V2.0.

**Comment by Integral-Tech** [comment]
> Interfaces that use user names and passwords often require secondary authentication (mobile phones or verification codes). These interfaces have strict requirements on IP addresses and other login environments. They are often blocked or even restricted for security reasons. Therefore, user names and passwords have been cancelled since V2.0.

Okay, thanks
